# plugin languages in /lang folder
lang: 'EN (US)'

# invites cooldown time (if player doesnt have bypass permission)
cooldown: 60 # per sec

luck-perms: true
# if this and luckperms are true and luckperms are loaded if you give a user a job rank player get him job!
# (async task) time = luck-perms-sync-time
luck-perms-async-users: true
# per second
luck-perms-sync-time: 10

# use playerholderAPI plugin?
placeholders: true

# auto save timing per second
auto-save: 3600 # per sec

#
# For example you can off generation default plugin jobs automatic
#
default-jobs: true

# listmembers size
listmembers: 54

listmembers-player:
  type: PLAYER_HEAD
  name: '&e&l%player_name%'
  lore:
    - ''
    - '&6Playtime: &e%seasonjobs_playtime_p_hours%'
    - '&6Warn: &e%seasonjobs_warns%/%seasonjobs_warns_max%'
    - '&6Point: &e%seasonjobs_point%&6/&e%seasonjobs_job_point%  &a&l%seasonjobs_cent_point%%'
  slots:
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43

listmembers-actions:
  next:
    - 49
    - 53
  back:
    - 45
    - 49
listmembers-items:
  filter:
    name: ''
    type: YELLOW_STAINED_GLASS_PANE
    lore:
      - ''
    slot:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 17
      - 18
      - 26
      - 27
      - 35
      - 36
      - 44
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
  next:
    name: '&aNext Page'
    type: GREEN_STAINED_GLASS_PANE
    lore:
      - ''
      - '&eClick to get next page'
    slot:
      - 53
  back:
    name: '&cBack Page'
    type: RED_STAINED_GLASS_PANE
    lore:
      - ''
      - '&eClick to back to old page'
    slot:
      - 45
  refresh:
    name: '&eRefresh Page'
    type: CLOCK
    lore:
      - ''
      - '&eClick to back to refresh the page.'
    slot:
      - 49