
name: SeasonJob
version: '1.0-SNAPSHOT'
main: org.parham.seasonjob.SeasonJob
api-version: '1.18'

softdepend:
  - Luckperms
depend:
  - PlaceholderAPI


commands:
  job:
    aliases:
      - 'job'
      - 'jobs'
      - 'gang'
      - 'gangs'
      - 'clan'
      - 'clans'