
name: SeasonJob
version: '3.0.3'
main: org.parham.seasonjob.SeasonJob

softdepend:
  - Luckperms
depend:
  - PlaceholderAPI


commands:
  job:
    aliases:
      - 'job'
      - 'jobs'
      - 'gang'
      - 'gangs'
      - 'clan'
      - 'clans'
      - 'staffteam'